secretcli q compute query secret1vgtmfvzdn7ztn7kcrqd7p6f2z97wvauavp3udh '{"get_config" : {}}' | jq > pair_staking_config_jsons/SHD_stkdSCRT.json
secretcli q compute query secret17ue98qd2akjazu2w2r95cz06mh8pfl3v5hva4j '{"get_config" : {}}' | jq > pair_staking_config_jsons/SHD_stATOM.json
secretcli q compute query secret1q36njy5vvxnacsjglzsccalmst23ve7qk4dua5 '{"get_config" : {}}' | jq > pair_staking_config_jsons/SHD_JKL.json
secretcli q compute query secret149n35d9av2vs874nc3y34n6ukmf49f3ygsmru6 '{"get_config" : {}}' | jq > pair_staking_config_jsons/SHD_BLD.json
secretcli q compute query secret1vzczp0z4edjamgcw9dc9y08v7h7vxwg5un229a '{"get_config" : {}}' | jq > pair_staking_config_jsons/stATOM_stOSMO.json
secretcli q compute query secret19wcw34ddys3d2geyunlf9hn3rz3ycf56pwxevf '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_stATOM.json
secretcli q compute query secret1zm2q7jl70cjk20tjpwflcedfch0ev64txm96zw '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_stkdSCRT.json
secretcli q compute query secret13j4n5gj8857h2j4cnempdkfygrw9snasx4yzw2 '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_SHD.json
secretcli q compute query secret13p8tzt9knzz3eq6u05qtmwjjwzx0cgckpw22us '{"get_config" : {}}' | jq > pair_staking_config_jsons/SHD_SIENNA.json
secretcli q compute query secret1jkxd060v6cl0ylj5g9lweg8vrykccpc3uauwrk '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_stOSMO.json
secretcli q compute query secret1mad087955ryfa8hxzjtpdrcj7m2qwz8mwa8k8a '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_stINJ.json
secretcli q compute query secret19zqa3hzgywnlt3cn9j9ml2g9uxugkte6n7kk70 '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_stkATOM.json
secretcli q compute query secret1nwx39c3wkz92v3mh5fauvca4ngjt76egu668r5 '{"get_config" : {}} '| jq > pair_staking_config_jsons/SILK_qATOM.json
secretcli q compute query secret1chx2cwjn0lnn387t7krzdu4mr4997z9ehaks8v '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_wETH.json
secretcli q compute query secret1nt24y379xjn096z6ep9n0ewlyda6jdmjymf2v4 '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_wBTC.json
secretcli q compute query secret17d5xmnkzm2z7376587nlltqgz24jvn5s6v9arm '{"get_config" : {}}' | jq > pair_staking_config_jsons/SHD_wBTC.json
secretcli q compute query secret12z88kzlqt8agtqsk50r56mxslfpx0k3lwmydu5 '{"get_config" : {}}' | jq > pair_staking_config_jsons/ALTER_stkdSCRT.json
secretcli q compute query secret1dmxmqc094rcwdxqfvycfj953zllwe7ejvwwzek '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_JKL.json
secretcli q compute query secret1mg86lhvjrswj732w5ztucj425fachvk65kz28s '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_HARBOR.json
secretcli q compute query secret1daq6wanf2avekg87unx9x3ze3wsvwhtg4m20kz '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_KUJI.json
secretcli q compute query secret1qgjv37xn24mf6pnurt4xqqrr73rthmech23lv4 '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_QCK.json
secretcli q compute query secret1jdzytfds8zvpj885rk6pkqje25g73ux29rtlgw '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_pSTAKE.json
secretcli q compute query secret12kwrx4jmzasj7sc4926l49dx5ry3rqnxzk3kny '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_STRD.json
secretcli q compute query secret1ldt92gzs07jx5mqwtrvpev89733jn88gjp0p3w '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_LUNA.json
secretcli q compute query secret1kw8d63a3945r42rgcx5x68f3a6ecfsxtg4zk46 '{"get_config" : {}}' | jq > pair_staking_config_jsons/stkdSCRT_SHILL.json
secretcli q compute query secret1ctgxt7tqrpjxqcqpz46hcch5cghcvx2kxkn4k7 '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_IST.json
secretcli q compute query secret1cxr62nxugnxmpde44spjpy5urqgwcfvrtdtnqg '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_CMST.json
secretcli q compute query secret1l0f53wjf0x8qdylrcha888gg4r5vrvlhhtpl0g '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_USDC.json
secretcli q compute query secret1sk5fj35xe0wdagu7dermas9q2u3tl4smvfahpz '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_USDT.json
secretcli q compute query secret1sdcqvyv96jk324y9vq9u6nljxs7palu85nh0wj '{"get_config" : {}}' | jq > pair_staking_config_jsons/SILK_USK.json
secretcli q compute query secret1hh9kgm00kfcjc78kefsf29g0fvxnd3f2tt9lrs '{"get_config" : {}}' | jq > pair_staking_config_jsons/ATOM_stATOM.json
secretcli q compute query secret1ygauj7gn3f4skj3x09erxhkujftu89s05drhyc '{"get_config" : {}}' | jq > pair_staking_config_jsons/OSMO_stOSMO.json
secretcli q compute query secret1v3v08kj7ngca3686hma5k02j8whdzp57qd4a8d '{"get_config" : {}}' | jq > pair_staking_config_jsons/JUNO_stJUNO.json
secretcli q compute query secret18dlxp9zu8kgkrr4qvlwdktvfdj9xen3kddc97j '{"get_config" : {}}' | jq > pair_staking_config_jsons/sSCRT_stkdSCRT.json
secretcli q compute query secret1rrwyqw9rx6rjyp6f6k05uwdemqxx0kltapkvca '{"get_config" : {}}' | jq > pair_staking_config_jsons/LUNA_stLUNA.json
secretcli q compute query secret1qvgkgtnelmqf2m6kjdaetws2geukdfpyp8t7qz '{"get_config" : {}}' | jq > pair_staking_config_jsons/INJ_stINJ.json
secretcli q compute query secret16h5sqd79x43wutne8ge3pdz3e3lngw62vy5lmr '{"get_config" : {}}' | jq > pair_staking_config_jsons/ATOM_stkATOM.json
secretcli q compute query secret1mr0eu9smlq4ac97rhr3np0nl8yq7k6n9gjm9t2 '{"get_config" : {}}' | jq > pair_staking_config_jsons/ATOM_qATOM.json


